fractalide/racket2nix

- racket2nix
> Problem: Dead code

- CONTRIBUTING.md
- racket2nix
Solution: point the generated default.nix to `minimal-racket`
solves #22
> Problem: full DrRacket installation fails to build

- racket2nix
Solution: Remove all progress feedback, and make progress too fast to be tracked.
>  Problem: Our progress feedback is spammy

- Makefile
- nix/racket2nix.rkt
Solution: Accept a number of --catalog parameters and read from those files instead.
Closes #2
> Problem: Figuring out dependencies requires network access

- .gitignore
- Makefile
- default.nix
Solution: Provide a default.nix
This means the Makefile, which wants to write a default.nix, has to
go. We will replace it with something much better shortly.
We cannot yet generate our own default.nix, this one is generated from
a massaged catalog and then itself massaged.
> Problem: We ourselves are not nix packaged

- nix/racket2nix.rkt
The unpack shell script refers to ${_htdp-lib} explicitly for its special-casing.
Solution: Make unpackPhase generic, move the special-casing out of nix and bash and into the generator.
> Problem: Cannot generate a correct nix file unless we include htdp-lib

- README.adoc
> Problem: No README with current build status

- default.nix
- nix/racket2nix.rkt
Solution: Cut out raco initial blurb, i.e. version and path dumps
> Problem: We are exceeding the log line limit of the Travis web UI

- test.nix
- travis-test.sh
Solution: Add log folding, one fold per derivation
> Problem: Travis log is difficult to overview

- README.adoc
Solution: Flesh out the README, and add contribution specifics there.
> Problem: Contribution guidelines don't mention project specifics

- README.adoc
Solution: Clarify that you need to install nix first.
> Problem: People may be discouraged if make doesn't work

- nix/racket2nix.rkt
- test.nix
- travis-test.sh
nix-build test.nix return code is being ignored
Solution: Tell bash to terminate early, fix the problem that was being ignored.
> Problem: travis-test.sh fails to fail

- nix/racket2nix.rkt
6442cd75 introduced two sources of log spam:
- accidentally included a disabling of the raco setup filter
- improved config.rktd so that raco pkg install now complains that it
finds the system collects twice
* this sadly does not allow us to remove the symlink workaround
Solution: Re-enable setup filter, introduce pkg install filter
Enable pipefail, so the filters don't cause install and setup failures
to go unnoticed.
> Problem: log spam is back

- nix/racket2nix.rkt
We have etc/racket/config.rktd, bin/racket, share/racket/links.rktd
and probably something more present in every racket package
derivation. This makes these derivations impossible to install
without getting clashes.
Solution: Use multiple outputs, 'out' and 'env'.
The things we explicitly do want to install, user-facing files, we
symlink from env to out. Currently that means only the contents of bin
minus racket.
Once we have man pages under control, those would make sense to put in
out too.
Closes #66
> Problem: generated derivations cause filename collisions

- nix/racket2nix.rkt
Solution: Create a 'main submodule.
> Problem: The command-line code is not separate from the library code.

- nix/racket2nix.rkt
It is an error for a derivation with circular build inputs to be
built. It should not have been depended on by anything. Until we
have fixed the root cause, treat it as a warning, and avoid doing
any work, so that 'make test' may go a little faster.
> Problem: shadowed dependencies are doing work

- catalog.nix
Solution: Use snapshot from the Internet Archive, also provide merged catalog.
> Problem: no live catalog available to nix

- travis-test.sh
Solution: Remove (import ./test.nix).pkgs, replace with nixpkgs.nix
> Problem: travis-test is not making use nixpkgs.nix

- stage0.nix
> Problem: stage0.nix not using nixpkgs.nix

- travis-test.sh
Solution: Bring over subfold improvements from fractalide/fractalide .
> Problem: no profiling in travis log

- .travis.yml
Solution: Add darwin to os list.
> Problem: not testing on darwin

- nix/racket2nix.rkt
We are letting Nix figure out what to name a source derivation, and
that affects the path name in share/racket/pkgs once that source is
installed by raco.
Up until now this has happened to work, because all dependencies have
designated a subdirectory within the git repo, but
fractalide/fractalide uses the root, and a package within
cardano-wallet couldn't depend on it because it was looking for
'fractalide' and the pkgs directory only had
'fractalide-<short hash>'.
Solution: Name the git source derivation explicitly.
We are still relying on ?path= derivations and non-git source
derivations to accidentally have the right name. For everything
on pkgs.racket-lang.org this still happens to be true.
> Problem: pkgs path name is implicit

- bump-nixpkgs.sh
- nixpkgs.nix
Solution: Bump nixpkgs.
Add bump-nixpkgs.sh to make this more convenient for next time.
>  Problem: darwin Travis is building racket-minimal from scratch 

- release.nix
Solution: Add release.nix
Hydra is ready to receive.
> Problem: not prepared for hydra.fractalide.com

- .travis.yml
- support/utils/setup-hydra.fractalide.com.sh
> Problem: not using hydra

- .gitignore
- release.nix
- support/utils/nix-build-travis-fold.sh
Solution: Hide Travis-specific things under isTravis.
Also add --fallback, so builds don't fail because hydra messed up.
>  Problem: hydra has evaluation errors 

- nix/racket2nix.rkt
Solution: Copy it as a fallback.
> Problem: hashed directory not always present

- release.nix
This means hydra won't make use of the darwin slave we added in
fractalide/fractalide-infra#3 .
Solution: Add it.
>  Problem: release.nix: No darwin build 

- build-racket.nix
- catalog.nix
- default.nix
- nixpkgs/bump-nixpkgs.sh
- nixpkgs/default.nix
- release.nix
- stage0.nix
- test.nix
This may cause unnecessary downloads on up-to-date machines.
Solution: Bump nixpkgs.
Add script for easily bumping nixpkgs.
> Problem: Our nixpkgs is over two months old

- Makefile
Solution: Correct spaces to tab
> Problem: Makefile: spaces for tab

- Makefile
> Problem: make release has the travis folds

- catalog.nix
Solution: Use write instead of print
> Problem: pretty-merged-catalog: quotes its output

- nix/racket2nix.rkt
- racket-packages.nix
Solution: Implement --thin mode.
Now you can do this:
$ nix-build -E "((import ./racket-packages.nix {}).extend ($(./racket2nix --thin ./nix))).nix"
/nix/store/3qkwgcsqycza6igzj2cz7wa9gkb95j4s-racket-minimal-7.0-nix
This pushes some transitive dependency resolution to Nix, but it stops
when it encounters pre-calculated transitive dependencies. It won't
run into the circular dependencies in the catalog, and if it runs into
any circular dependencies outside the catalog, the user is to blame.
The main direct gain from this is that we can easily skip the catalog
generation step when building packages with dependencies not in the
racket catalog.
The generated expression looks like this:
$ ./racket2nix --thin ./nix
self: super: {
nix = self.lib.mkRacketDerivation rec {
pname = "nix";
src = …
> Problem: No generator for extensions to racket-packages.nix

- update-racket-packages.sh
> Problem: Didn't actually add update-racket-packages.sh

- build-racket-default-overlay.nix
- build-racket.nix
Solution: Implement buildRacket overlays, put gui-lib overrides in default overlay.
> Problem: gui-lib: Implicit dependency on icons

- nix/racket2nix.rkt
Solution: Move mutual exclusion to command-line declaration
> Problem: --flat vs --thin: Explicit check for exclusion

- build-racket.nix
- default.nix
- pkgs/default.nix
- stage0.nix
- stage1.nix
Solution: Implement and export buildThinRacket{,Package}
- Verify in stage1.
>  Problem: API: Not exporting --thin functionality

- build-racket.nix
The hack to correct the directory name of the source only works when
running buildThinRacket on non-store paths.
In concrete terms: fractalide doesn't build with buildThinRacket.
Solution: Replace builtins.path with a fixed-output derivation.
This should duplicate the fixedRacketSource fixed-output derivation
that racket2nix creates anyway, so in the end no extra disk work is
actually done. Actually this probably saves work running racket2nix
when the same source is used in different contexts.
> Problem: Cannot use builtins.path on store paths

- release.nix
Solution: Add check that it's up-to-date with the generator.
> Problem: release.nix: No check for racket-packages.nix

- build-racket-default-overlay.nix
- nix/racket2nix.rkt
- racket-packages.nix
Solution: Fix gracket, library lookup and drracket dependencies.
> Problem: We cannot build and run drracket

- nixpkgs/bump-nixpkgs.sh
- nixpkgs/default.nix
- racket-minimal/default.nix
> Problem: hydra detects a failed sha256 match

- nix/racket2nix.rkt
- racket-packages.nix
Solution: Provide installCheckFileFinder.
> Problem: No hook for packages to select test files

- nix/racket2nix.rkt
Whenever some minor thing is changed in catalog processing, or when we
bump upstream catalogs, the existing mapping from URLs and sha1s to
sha256s is thrown away, and the repos in the whole catalog need to be
fetched, which takes on the order of hours.
Solution: Prime the sha256 cache from the existing catalog.
A change to update-catalog, racket2nix or the upstream catalogs now
needs to download and check only those sources that changed.
./update-catalog.sh now runs in around half a minute when only the
source code changed, none of the data.
> Problem: update-catalog: Always resolves sha256s from scratch

- release.nix
Solution: Remove Darwin from release.nix.
> Problem: Hydra fails evaluation b/c Darwin down

- integration-tests/default.nix
This was made apparent by #271 / ff4dc0d and running tests on a clean
machine. Before that fix, it worked because the fixed-output
derivations were being downloaded from hydra.
This is one of those "but how could this have ever worked" things. Not
sure if something changed in Nix or racket2nix that made it not work.
Solution: Use direct derivations instead of generated fixed-output.
This means overriding the racket-packages output from buildRacket.
There is opportunity here for several usability fixes that would make
the fix less kludgy, and which would benefit real buildRacket users.
It should be possible to use buildRacketCatalog and buildRacket
together and it Just Works, or even better, not having to use
buildRacketCatalog.
For well-behaved packages there is buildThinRacket, which …
> Problem: test fixed-output srcs work by accident

- build-racket-default-overlay.nix
- nix/racket2nix.rkt
- racket-packages.nix
Solution: Move it to the default overlay.
> Problem: racket-index's patch is hardcoded

- build-racket-default-overlay.nix
- nixpkgs/default.json
- racket-packages.nix
- release-catalog.json
- test.nix
Solution: Bump and update all the things.
(except live catalog, that's up to date)
>  Problem: Not running Racket 7.3

- build-racket-default-overlay.nix
These packages build fine without their overrides.
Solution: Remove the overrides.
> Problem: Some overrides outdated

- build-racket-default-overlay.nix
- nix/racket2nix.rkt
- racket-packages.nix
Solution: Make the timeout customizable
- Double the brag-lib timeout (test-all takes 80 s).
> Problem: Some tests go over the timeout

- .travis.yml
Solution: Upgrade nix before running tests.
> Problem: Travis Nix is out of date
