racket2nix

Solution: Remove duplicates in package->derivation, not just in
package->transitive-dependency-names.
Closes #14

Problem: Redundant transitive dependencies

---

racket2nix

When the erroneous condition would occur (tested with intentionally
faulty code), the exception contructor would be called incorrectly:
exn:fail:contract: arity mismatch;
the expected number of arguments does not match the given number
expected: 2
given: 1
arguments...:
"Circular dependencies are supposed to be culled."
Solution: Use the convenience function instead, and supply better
arguments.
The correct exception (which never happens):
name->transitive-dependency-names: contract violation
expected: not supposed to be a circular dependency
given: "racket-doc"
argument position: 1st
other arguments...:
'("rackunit-doc" "racket-doc" "drracket")

Problem: Exception constructed incorrectly

---

racket2nix

Solution: Use strings, not variable references.

Problem: circularBuildInputs makes our builds circular

---

racket2nix

Problem: Skipping circular dependencies breaks install
When we simply do not install a circular dependency, the dependant
fails to install due to the missing dependency.
Solution: Remove the dependencies inside the packages when installing.
We go inside the info.rkt and remove all references to the circular
dependency.
This works for the test set of racket-doc with transitive
dependencies.
drracket builds again, and this time it's not empty. It's not complete
though, that's for issue #23.
Closes #19

Circular builds redux

---

racket2nix

Solution: Fix the collects dir issue and the setting up to much stuff issue. Run raco setup.
This doesn't solve the fact that we are not building clean, we're reusing the bytecode others compiled. But at least the setup is not incomplete. We'll have to do our own cleaning from what I can tell, so we'll have to get back to that in #34.

Problem: We are not running raco setup

---

racket2nix

Solution: Escape the tilde in '~2048', add missing apostrophe.
Closes #37.

Problem: template text invalid format string, missing apostrophe

---

racket2nix

Solution: Set up links-search-files correctly
This releases a whole can of worms, because several dormant mechanisms suddenly come into play.
These commits are a step toward solving #3, and they also partially solve #34, while giving rise to #38 and #39.

Problem: links-search-files is set up incorrectly

---

Makefile
info.rkt
nix/racket2nix.rkt

This means we can't parameterize what we are doing. We need this for
several things.
Solution: Start by making the package to process a command-line argument
instead of being input through stdin.

Problem: We are not parsing the command-line

---

generate-default.nix
pkgs-nix
test.nix

Solution: Create a nix derivation that depends on generation of our
default.nix and verifies that it didn't change.
It's not yet correct, because our default.nix is ahead of what
racket2nix can generate, but it's a great tool for getting us there.

Problem: No automated testing

---

nix/racket2nix.rkt
test.nix

The nix-packaging commit broke the racket-doc build, by making circular leafs not even build.
Solution: Correct the if case, and make building racket-doc our main test case, so we don't break it again.
Run the test by doing nix-build test.nix.

Problem: We broke racket-doc

---

nix/dump-catalogs.rkt

As it is used by a fixed-output derivation, I never noticed that I
only had it locally, even when trying in a fresh worktree.
Solution: Add dump-catalogs.

Problem: dump-catalogs is missing

---

.travis.yml
travis-test.sh

Solution: Add .travis.yml and call make test
We'll see how long this takes to run on Travis, probably ~45 minutes. I kind of want it for now anyway, but the future is writing synthetic packages to test on, which can exhibit all the corner cases that the release pkgs do.

Problem: We are not running tests on PRs automatically

---

nix/racket2nix.rkt
pkgs-nix
update-default.nix

We need packages to be present in our catalogs in order to process them.
Solution: If package name contains at least one slash, treat it as a directory.
Synthesize a package entry from the directory.
Use this mechanism to package ./nix.
Closes #3
Closes #4

Problem: We cannot create expressions directly from directories

---

README.adoc

I tried to generate the HTML for the README locally, and got:
asciidoc: ERROR: README.adoc: line 4: only book doctypes can contain level 0 sections
I caused this when I made the update to README before, as I figured it doesn't seem
to make sense to not make use of all the levels. I stand corrected.
Solution: Add one level to all headlines.

Problem: README is not valid asciidoc

---

README.adoc

Solution: Escape the hash characters with passthrough markup.
Found the solution in asciidoctor/asciidoctor#1326 .

Problem: riot link is broken

---

Makefile
travis-test.sh

Solution: Remove pkgs-nix dependency from Makefile
Add plain make to test sequence to prevent this from happening again.

Problem: Makefile requires a pkgs-nix file that is no longer there

---

default.nix
nix/racket2nix.rkt

Solution: Make an mkRacketDerivation function for the common parts.
Before:
$ wc -l /nix/store/4nk02bzi0481rza5z42r1ns7c5fhh6ry-racket-doc.nix
15720 /nix/store/4nk02bzi0481rza5z42r1ns7c5fhh6ry-racket-doc.nix
After:
$ wc -l /nix/store/mchqr7fb5xxkg0adv31wbii37i6akvpd-racket-doc.nix
2915 /nix/store/mchqr7fb5xxkg0adv31wbii37i6akvpd-racket-doc.nix
Closes: #5

Problem: lots of redundant code in generated nix

---

Makefile
update-default.nix

We would still catch it in Travis when we build racket-doc, but better
to catch it early.
Solution: Use an unpackaged racket2nix to create a default.nix, make a
new racket2nix from that, run again, compare outputs.
This replaces and improves the test in Makefile (you would have to run
the original `make` twice to get the equivalent), so we can lift that
out. If nix-build returns something, it's tested.

Problem: `make` doesn't test that self-hosted racket2nix works

---

default.nix
nix/racket2nix.rkt
test.nix

Solution: adapt config.rktd, create a racket wrapper, fake a lib-dir
The real solution is to patch racket to use search paths for lib and bin.
Our solution here is polluting bin so that a user can't trivially
install a racket2nix-generated derivation along with racket or
another generated derivation.
See #66 for more on filename pollution.
Closes #41

Problem: launchers aren't getting created

---

Makefile

This makes the test a bad indicator on whether we broke something new.
Solution: Build racket-doc prerequisites, but not racket-doc.
Go back to building racket-doc as soon as we got it working.

Problem: we are failing on a known issue

---

catalog.nix
default.nix
stage0.nix
test.nix
travis-test.sh

For nix to know whether `racket2nix // attrs` is allowed or not, it needs to
build `racket2nix-nix` so it can evaluate `racket2nix`. This is confusing and
stops e.g. pre-fetching from being exactly what it looks like.
Solution: Split out stage0.nix and catalog.nix

Problem: cannot reach attrs in default.nix without building racket2nix-nix

---

nix/racket2nix.rkt

This just happened locally when bootstrapping racket2nix. Took me
hours of looking for faults in the wrong place.
Solution: Remove all *.zo before installing.

Problem: we may accidentally install old code

---

travis-test.sh

The pipe to awk makes awk's the only exit code considered within that
pipe.
Solution: Set 'pipefail'.
If this change fails, it was successful. Now let's fix that
deinprogramm issue and make success mean success.

Problem: Travis still failing to fail

---

nix/racket2nix.rkt

Solution: Add manual descriptions of the cycles.
This gives us a green build again. From here we can work on the real
solution. I have a plan.
We are still not trying to build racket-doc itself. I put hours into adding
manual cycles, and it led nowhere. We need to do this properly.

 Problem: racket-doc deps don't build due to circularity 

---

catalog.nix
default.nix
stage0.nix

We actually never use anything outside ./nix for our derivations, and
capturing all of ./.  means you get spurious builds just because you
happened to have a temporary file or a ./result link in there.
Solution: Change racket-catalog, racket2nix-stage0 and racket2nix to build from ./nix instead.

Problem: src = ./. is too wide

---

nix/racket2nix.rkt
test.nix
travis-test.sh

Solution: Instead of hard-coding that we expect any unexpected
packages to be in the racket-lib (racket) derivation, ask the runtime
what scopes there are.
Also, check per package to install, not for all packages based on what
package our name says we are mainly packaging.
travis-test.sh: Verify that racket2nix builds against full racket
too.

Problem: We have a hard-coded assumption in the skip-install code

---

nix/racket2nix.rkt

This is slow and makes the setup order-sensitive.
Solution: Run raco setup on a list of packages, just like with raco pkg install.

Problem: we are setting up packages one by one

---

Makefile
travis-test.sh

When we extracted catalog.nix we forgot to update Makefile.
Solution: Make Makefile refer to catalog.nix instead of the non-existent racket-catalog attribute.
Add 'make pkgs-all' to travis-test.sh.

Problem: make pkgs-all stopped working

---

nix/dump-catalogs.rkt

The begin is implied in command-line after #:args.
Solution: Remove the begin in dump-catalogs.

Problem: unnecessary code in dump-catalogs

---

catalog.nix
default.nix
racket-minimal.nix
stage0.nix
test.nix

The system libiconv doesn't support UTF-16, which is used in one of
the code examples in the documentation.
Solution: On darwin, override racket-minimal to use GNU libiconv
Put the racket-minimal override in its own file and import
everywhere.

Problem: darwin cannot build drracket (PR nixpkgs#35429)

---

travis-test.sh

racket2nix now has dependencies, and the folds we have are too coarse.
Solution: Bring back the derivation folds filter, and apply it within
each major fold to produce sub-folds.
Travis doesn't actually have sub-folds, so let's emulate them.
The most interesting folds are the last of the
..-nix.drv..racket2nix and ..-nix.drv..racket2nix.full-racket folds,
because that's where the tests run. Maybe we should highlight that
somehow, but if the tests fail it becomes unfolded and obvious, so
it's not a priority for now.

Problem: our Travis folds are too spammy

---

default.nix

Solution: Create racket2nix-env in default.nix, which depends on racket2nix.

Problem: no trivial way to put racket2nix in your PATH

---

Makefile

It's just slightly inconvenient when the path to a working racket2nix
is not the last line in the output from a plain 'make'.
Solution: Put racket2nix last in default target.

Problem: `make` calls racket2nix-flat-nix last

---

nix/racket2nix.rkt

As we are moving closer to successfully compiling htdp-lib and
racket-doc, we are once again running into to low max-file ulimit
on macOS.
Solution: Raise maxFileDescriptors to 3072.

Problem: We are running out of file handles again

---

Makefile
nix/racket2nix-test.rkt
nix/racket2nix.rkt

Solution: Replace the quick rewrite-parents hack with proper cycle percolation.
Also:
- `make test` builds racket-doc again, because that works again.

Problem: failure to detect one branch in diamond circular dependencies

---

nix/racket2nix.rkt

When circular dependency detection is merged, these exceptions will be redundant.
Solution: Remove redundant code.

Problem: redundant code from trial-and-error

---

default.nix
nix/racket2nix.rkt

Solution: Implement support for git and github sources.
Known limitations:
Fractalide only builds with full racket, due to #94 giving us
empty.zip for release packages.
Closes #77
Closes #20

Problem: we cannot package fractalide

---

test.nix

Solution: use fetchFromGithub which downloads just the
tarball at that revision

Problem: fetchgit fetches the entire history

---

default.nix
nixpkgs.nix
test.nix

If some other nix expression imports us remotely, they cannot trust
that racket2nix will always build, because it's using <nixpkgs> for
pkgs.
Solution: Extract nixpkgs pinning from test.nix and use it in both
test.nix and default.nix.

Problem: default.nix nixpkgs is not pinned

---

nix/racket2nix.rkt

The regular expression is valid on Nix/Linux but not on Nix/Darwin.
Solution: Use builtins.split instead.
Closes #100

Problem: extractPath doesn't work on Nix/Darwin

---

nix/racket2nix.rkt

Solution: Use lib.splitString.

Problem: builtins.split is nix 2.0

---

Makefile
merge-hashes.rkt
test.nix
travis-test.sh

Solution: Add builds for typed-map-lib and br-parser-tools-lib.
- typed-map-lib: uses git, dependency of fractalide, so we are
testing that we can supply fractalide
- br-parser-tools-lib: has a slash in the path= query, so we
are testing the string split
Now that we have light tests, add them to travis.

 Problem: no tests verifying git and string split

---

build-racket.nix
catalog.nix
default.nix

Solution: Extract the nix generator function and caller into build-racket.
Make it more convenient to use.
Export as buildRacket in default.nix for others to use.

 Problem: no convenient API for building Racket derivations 

---

nixpkgs.nix

This results in us having to build some things that fell out of the
hydra cache.
In particular, we are building Nix 2.0 on travis darwin.
Solution: Bump nixpkgs.
Tested fractalide/fractalide bumped to this racket2nix, and darwin build times go down from 1600 s to 800 s, as Nix is not rebuilt.

Problem: Our pinned nixpkgs is old

---

travis-test.sh

The test in `travis-test.sh` is broken.
Solution: Fix broken import, and use the `meta.available` attribute to simplify.

Problem: not testing racket2nix with full racket

---

build-racket.nix
default.nix
nix/racket2nix.rkt
stage0.nix

```
$ nix-build --option restrict-eval true \
-I . -I /nix/store/8wpfckjbdwhrfrfdra6gi2f69brdyz20-nixpkgs-18.09pre140705.090b7cc8f1b/nixpkgs \
build-racket.nix --arg package ./nix
building '/nix/store/dh56a2qmy6x65pzscxn85dkr74pkbx9v-racket-package.nix.drv'...
installing
error: access to path '/nix/store/x8fbigk4ms45j7dpfcdi97x834mmynrd-racket-package.nix-src/nix' is forbidden in restricted mode
```
Solution: When a package is located inside the store, racket2nix
refers to it as a no-op fixed-output derivation instead of as a plain
path. Example:
```
fractalide/fractalide/pkgs $ nix-build --arg racket2nix 'import ../../racket2nix {}' -A fractalide.nix | xargs grep -m 1 -A 5 _fractalide
_fractalide = mkRacketDerivation rec {
name = "fractalide";
src = fixedRacketSource {
pathname = …
```

Problem: build-racket does not work with restrict-eval = true

---

default.nix
test.nix

`nix` is missing as a dependency in two places, partly due to #129.
Solution: Add nix dependency.

Problem: travis fails with missing nix-instantiate

---

build-racket.nix
nix/racket2nix.rkt
support/utils/nix-build-travis-fold.sh

The `racket-package.nix.src` dance is for the purpose of making sure
the racket derivation depends on the subtree only, and not the whole
source repo. Now we have the fixed-output dance, which takes care of
that too.
Solution: Remove the `src` output from the `racket-package.nix`
derivation.
Add build-racket-packaged nix to the Travis tests, while also phasing
in use of nix-build-travis-fold.sh.
This nix-build-travis-fold.sh also uses restrict-eval, so that we
catch those issues before we reach Hydra.

Problem: racket-build has unnecessary complexity

---

support/utils/nix-build-travis-fold.sh

1. The readlink returns empty string, so the arguments get misaligned.
2. If it would work, the lack of an include path means the
restrict-eval would complain.
Solution: Quote the include paths, add `profiles/per-user/root`.
The test environment on Travis darwin finds nixpkgs in
`/nix/var/nix/profiles/per-user/root/channels`.

Problem: nix-build-travis-fold fails on Travis darwin

---

nix/racket2nix.rkt

$ ~/git/fractalide/racket2nix/racket2nix --catalog catalog.rktd /nix/store/h7s2sqjx0jfj6w0a7x7wh7vaw35hivw9-fractalide > h7s2.nix && nix-build --no-out-link h7s2.nix
/nix/store/8138lplmikk6cpiqrqrd5iy5bg63vdqk-h7s2sqjx0jfj6w0a7x7wh7vaw35hivw9-fractalide
Solution: Implement and use (strip-store-prefix).
$ ./racket2nix --catalog catalog.rktd /nix/store/h7s2sqjx0jfj6w0a7x7wh7vaw35hivw9-fractalide > h7s2.nix && nix-build --no-out-link h7s2.nix
/nix/store/4wl3dyz14ljj1nnnr8rszan3xgpk662b-fractalide
Closes #135

Problem: not stripping off the store prefix and hash off package name

---

nix/racket2nix.rkt

```
open-output-file: cannot open output file
path: /nix/store/r25bh9mk7n51rkxsm5q1n96dd0rv92aq-scribble-lib-env/share/racket/pkgs/scribble-lib/scribble/doc/lang/compiled/tmp15284803211528480321753
system error: Permission denied; errno=13
compilation context...:
/nix/store/mjqwdni00nnsv0f8qb13nqg91k9ihl60-memoize-env/share/racket/pkgs/memoize/memoize/memoize.scrbl
```
Solution: Add memoize with scribble-lib to `force-reverse-circular-build-inputs`.

Problem: memoize does not build

---

support/utils/setup-hydra.fractalide.com.sh

Result: hydra.fractalide.com cache is not being used.
Solution: Kick nix-daemon, so that it reloads conf.
This only affected darwin, because linux Travis uses single-user Nix.
Don't fail if there is no nix-daemon.

Problem: darwin: nix.conf didn't take

---

default.nix

We want this when cross-building other things using buildRacket.
Solution: Provide a system parameter in /default.nix.

Problem: No trivial way to override system

---

default.nix

It's spelled builtins.currentSystem, not builtins.system.
release.nix sets pkgs explicitly, so default.nix never had to fallback
to the system parameter. But when building with default.nix directly,
build fails.
Solution: Use builtins.currentSystem as the system default.

Problem: Simple nix-build broken

---

nix/racket2nix.rkt

It's really useful to be able to override a function call and have
access to the parameters of the original call.
In particular, this is important if you want to buildRacket and then
modify the parameters of the derivation it generates.
Solution: Add overrideRacketDerivation to mkRacketDerivation output.

Problem: No equivalent of overrideAttrs

---

default.nix
stage0.nix

The racket2nix bootstrap refers to ../nix, then has to override it
when using the generated nix file. It can just refer to the nix
store alias instead to make it non-relative and remove the need
for an override.
Solution: Refer to $src instead of ../nix in the bootstraps.
Also make stage0 look more like a buildRacket-generated derivation.

Problem: Some outdated workarounds are still around.

---

nix/racket2nix.rkt

If you have several packages not in the catalog and want them to
depend on each other, you need to first generate a catalog for them.
Solution: Allow several package paths on the command line.
Package paths after the first one will be treated as supplemental and
used if the first one depends on them.
Closes #157

 Problem: No way to supply supplemental package paths

---

build-racket.nix
default.nix
integration-test/a-depends-on-b/info.rkt
integration-test/a-depends-on-b/main.rkt
integration-test/b-depends-on-c/info.rkt
integration-test/b-depends-on-c/main.rkt
integration-test/b-depends-on-c/what-c-needs.rkt
integration-test/c-depends-on-b/info.rkt
integration-test/c-depends-on-b/main.rkt
integration-test/catalog.nix
integration-test/catalog.rktd.in
integration-test/default.nix
integration-test/update-catalog-sh
nix/racket2nix.rkt
test.nix

Flattening makes all your deps circular deps, which is supposed to
mean everything gets compiled in one big derivation. But it's not that
simple.
- The reverseCircularDeps mechanism makes the assumption that the
catalog resolver went through the circle and added all the deps as
reverse circular deps to the top derivation.
- The flatten mechanism makes the assumption that adding a dep to
reverseCircularDeps is enough.
Solution: reverseCircularDeps: Don't add the src, add the srcs.
Each derivation calculates srcs from its own reverseCircularDeps, so
this makes srcs accumulate all the packages necessary. Unfortunately,
this means it adds redundant srcs, so we can't be as strict about
those any more. We'll silently skip unpacking a src with a name that
we already unpacked.
This is the quick …

Problem: Flattening fails to include some deps

---

test.nix

`generateNix` and `buildPackage` in test.nix are redundant with `buildRacket`.
Solution: Refactor test.nix to use buildRacket.

 Problem: Repeating ourselves in test.nix

---

racket-minimal.nix

Typo: stdenv instead of nixpkgs
But we never made use of the default, so it went unnoticed.
Solution: Use the pinned nixpkgs as default instead.

Problem: racket-minimal: The pkgs default never worked

---

integration-test/default.nix
test.nix

The `system` and `racket` properties don't propagate properly down to
the `integration-test` expression.
Solution: Replace imports with `callPackage`, make sure to pass that
`racket` along.
Closes #163
I think the trouble in these commits shows that having racket
explicitly passed everywhere is a problem. It's better to make
a proper overlay to pkgs, and parameterize racket that way instead.
It's not as simple as overlaying `racket = self.racket-minimal`, as
racket-minimal is a derivative of racket and that creates a recursion.
Instead, racket-minimal is going to have to be derived from a grounded
nixpkgs.
I'm thinking that the best way is probably to import a grounded racket
as racket-full, dump nixpkgs racket-minimal (it's not many lines) into
our repo, and make it derive from …

 Problem: Hydra builds Darwin integration tests on Linux

---

build-racket.nix

default.nix handles the command-line call to buildRacket, but
build-racket.nix still has it too.
Solution: Remove one-liner code from build-racket.nix.

Problem: No need for two one-liners

---

Makefile
build-racket.nix
catalog.nix
default.nix
pkgs/default.nix
release.nix
stage0.nix
stage1.nix
support/utils/nix-build-travis-fold.sh
test.nix

The new pkgs construct and a general annoyance with one too many "yeah
I'll get around to that thing" provide an excellent combination for a
major refactoring round.
We have things not making use of neat nixpkgs constructs I didn't know
about half a year ago, and we have things that have grown organically
out of control and are in need of some structure.
We are repeating ourselves all over the place.
Solution: Refactor And Fix All The Things.
- mkDerivation -> runCommand or buildEnv
- (buildRacketPackage "yourpackagenamehere").flat
- stage0 refactor to look more like buildRacket
- stage1 refactor to use buildRacket
- pkgs.overridePkgs (after-the-fact overlays!) used by stage1 to get
a flat stage0 for flat stage1 while still using buildRacket
- racket2nix.buildEnv
- clean fix replacing the …

 Problem: Accumulated technical debt

---

default.nix

Solution: Allow passing overlays to default.nix.
Want to use full racket?
nix-build /path/to/racket2nix --argstr package thepackage --arg overlays '[ (self: super: { racket = super.racket-full; }) ]'

Problem: No way to tell one-liner to use racket-full

---

nix/racket2nix.rkt

Case in point: racket2nix itself is a package called `nix`, which
collides with the derivation of the nix package manager itself.
Solution: Prepend `$racket.name` to the package derivation name.
This has the added advantage of also distinguishing racket versions,
and even racket-full vs racket-minimal.
Also it solves another minor issue, which is that of distinguishing
the package derivation from the package source derivation.
Closes #127

Problem: Our derivation names may collide with nixpkgs

---

catalog-overrides.rktd

There's an incomplete `(build .` in `catalog-overrides.rkt`, stemming from:
71b9f47bda13f5067f32c86ac013228910947ac7
#177
Solution: Remove stray characters.

Problem: catalog-overrides.rkt: Stray lines

---

nix/racket2nix.rkt

Solution: Send `-j $NIX_BUILD_CORES` to `raco setup`.
- If your build fails, you can run `nix-build --cores 1 ...` to get
nice linear output and see exactly where `raco setup` failed.

Problem: Our derivations don't respect --cores

---

README.adoc

A user just discovering racket2nix has no idea how easy it is to turn
your racket package into a Nix derivation.
Solution: Add Quick start guide to README.

 Problem: No Quick start guide

---

build-racket.nix
pkgs/default.nix

When you're in the situation where you have several packages not
published on pkgs.racket-lang, you have to create provisional
catalogs, patch them for internal vs external use, and run update
scripts outside Nix. See fractalide/cardano-wallet for the machinery
required.
Solution: Provide buildRacketCatalog, which takes several packages,
potentially with dependencies among themselves, and merges their
definitions with the default catalog to create a catalog that can
build either one of the packages.
Making one catalog per package and then merging them is a bit clunky,
and the real solution is to implement export of several packages in
racket2nix, but I'd like to kick that can down the road a bit, and
this workaround in Nix was quick and easy.
To be concrete, this is the kind of thing this …

Problem: No API for building catalogs

---

catalog.nix
nixpkgs/default.nix

Racket 7.0 is now in nixpkgs-unstable.
Solution: Bump nixpkgs, bump release catalog.

Problem: Not using Racket 7.0

---

nix/racket2nix.rkt

The launcher creation calls (make-relative-path-header), which peeks
at the filesystem for certain tools. How the output looks depends on
what it sees, and varies between sandboxed and non-sandboxed builds.
Solution: Set absolute-install? to #t in config.rktd.
This gets us a plain, hard-coded directory reference for launchers to
look for racket.
Closes #194
Makes any worries in #186 obsolete.

Problem: Launcher creation is not pure

---

nix/racket2nix.rkt

Solution: Use makeExtensible.
Closes #175
- Wrap all the dependencies in an attribute set.
- Export that attribute set as an attribute of the package.
- Wrap the attribute set in a function called with makeExtensible.
- Move our functions into a sub-attribute 'lib', minimize collision.
- Take the chance to rename attributes to names without a '_' prefix.
Example:
$ nix-build -A racket-packages.racket2nix
error: attribute 'racket2nix' in selection path 'racket-packages.racket2nix' not found
$ nix-build -A racket-packages.nix
/nix/store/l5dnla8gjg04v7v4q8pzkqaxqgp0l8cd-racket-minimal-7.0-nix
$ nix-build -E 'with import ./. {}; (racket-packages.extend (self: super: { racket2nix = self.nix.overrideRacketDerivation (oldAttrs: { pname = "racket2nix-stage1"; }); })).racket2nix' …

 Problem: Output is not composable

---

Makefile

Now we have sed to remove those pesky carriage returns. And that
`echo` should have been an `@echo` to begin with.
Solution: Remove `echo`.

Problem: Makefile: release: echo is redundant

---

nix/racket2nix.rkt

.rkt scripts with a shebang for running racket get patched for running
the plain racket binary, instead of the wrapper that sets up the
environment and allows the file to actually run.
Solution: Add the wrapper to PATH when building.
Before:
$ head -n 1 $(nix-build -A racket2nix.env)/share/racket/pkgs/nix/racket2nix.rkt
#!/nix/store/gz8l5riy8ppvnqk1vfkan65wwk82pjka-racket-minimal-7.0/bin/racket
After:
$ head -n 1 $(nix-build -A racket2nix.env)/share/racket/pkgs/nix/racket2nix.rkt
#!/nix/store/lxsk3qk4f8lrym9c1sxjcxhv3zcjky0d-racket-minimal-7.0-nix-env/bin/racket

Problem: 'patching script interpreter paths' wrong

---

integration-tests/a-depends-on-b/info.rkt
integration-tests/a-depends-on-b/main.rkt
integration-tests/b-depends-on-c/info.rkt
integration-tests/b-depends-on-c/main.rkt
integration-tests/b-depends-on-c/what-c-needs.rkt
integration-tests/c-depends-on-b/info.rkt
integration-tests/c-depends-on-b/main.rkt
integration-tests/default.nix
release.nix

Solution: Convert package tree unit tests to integration tests.
Instead of the manually written packages, generate racket packages
with the full range of complications:
- Long circles
- Circles within circles
- Independent circles depended on by other circles
This would have caught a thing or two that I encountered while
working on the new circle resolver (while the unit tests had not yet
been adapted).
For now, just verify that the packages build. The code in the packages
expresses the dependencies, so any missing dependency will cause a
compilation error.

Problem: integration-tests are simplistic

---

racket-minimal/default.nix

The basename of the source is racket-minimal-src.tgz, the version is
only reflected in the directory name.
We forgot to update the sha256 or the fixed-output derivation, so it
just used the old source under a new derivation name.
Solution: Update the sha256.
Nixpkgs has this issue too on nixpkgs-unstable. Fixed on master.

Problem: Our racket-minimal-7.0 is a 6.12 disguised as 7.0

---

nix/racket2nix.rkt

This won't hold for synthesized packages representing cycles
("reified cycles").
Solution: Check for a `src` attribute, and just use null otherwise.
We could have used no src attribute at all, but flat builds expect
all transitive dependencies to have a src attribute.

Problem: mkRacketDerivation: Requires packages to have a src

---

build-racket.nix

stage1.nix uses it to add deps etc to the stage1 derivations.
Solution: overrideAttrs attrOverrides

Problem: buildRacket: attrOverrides ignored

---

nix/racket2nix.rkt

The hash looks unfamiliar, because base32 is the encoding usually used
when writing nix derivations.
Solution: Call nix-hash with --base32.

Problem: discover-path-sha256: base16

---

build-racket.nix

Solution: Refer to the correct variable.
The problem was disguised by caching of the derivation.

Problem: build-racket: The fixed-output derivation fails

---

release.nix

Solution: Add tests to release.nix.
Choose gui-lib for the string test to regression-test the override.

Problem: one-liner: No tests

---

nix/racket2nix.rkt
racket-packages.nix

/nix/store/jkb56ipz7yckrw7imqqfmjjjp90pvs3r-racket-minimal-7.0/bin/racket -G /nix/store/9h5c1qgxkkjj2l7jkld3ijas39sy4xyf-racket-minimal-7.0-fractalide-env/etc/racket -U -X /nix/store/9h5c1qgxkkjj2l7jkld3ijas39sy4xyf-racket-minimal-7.0-fractalide-env/share/racket/collects
find: 'chmod': Argument list too long
Supposedly find splits the arguments into several calls so that this
should not happen. Apparently that's not reliable.
Solution: Use xargs instead.

Problem: darwin: argument list limits

---

nix/racket2nix.rkt

Our method for finding out whether racket2nix is running inside a Nix
derivation (i.e. called from buildRacket) ironically cannot run inside
a Nix derivation, if the sandbox is enabled.
building '/nix/store/bksdhdyj4hw5ply332zypxmf8rxy9dik-racket-package.nix.drv'...
error: creating directory '/nix/var': Permission denied
builder for '/nix/store/bksdhdyj4hw5ply332zypxmf8rxy9dik-racket-package.nix.drv' failed with exit code 1
What it really wants to find out is whether its inputs are in the Nix
store and need to be wrapped in a fixed-output derivation to pass
strict evaluation.
Solution: For now, hard-code the store path as '/nix/store'.
Honestly, it not being '/nix/store' is an extreme corner case that may
not even work. It just didn't feel right to hard-code it.
Closes #226

Problem: nix-instantiate cannot run in the sandbox

---

Makefile

Nix canonicalizes the path to release.nix and complains that it cannot
be read in strict mode.
Solution: Canonicalize the path in the nix-build -I parameter.

Problem: make release: Does not work if on a symlink path

---

catalog.nix

openssl: x509-root-sources: cert sources do not exist: "/no-cert-file.crt", "/nix/store/n5k0bwl54gnpdhv24rk2l5s9gs4x8f2j-openssl-1.0.2p/etc/ssl/certs"; override using SSL_CERT_FILE, SSL_CERT_DIR
We do not actually access the network in this derivation, but someone
might be put on the wrong trail by the warning message.
Solution: Silence the warning by setting SSL_CERT_FILE.

Problem: mergedUnfilteredCatalog: SSL_CERT_FILE warning

---

support/utils/nix-build-travis-fold.sh

I read the link and now the parameters are -I nixpkgs=/nix/store/y59cw26mvxrkn9qjv1dc5lzxkwjgpdxk-nixpkgs-19.03pre151875.7c1b85cf6de/nixpkgs
This was introduced in #170 (cleanup), commit:
1e321dda94cd2c2f053d35a9c50e6b3269e04daa
Solution: Remove it.

Problem: nix-build-travis-fold: Obsolete debug output

---

release.nix

<3>raco setup: docs failure: make-directory: cannot make directory
<3>  path: /homeless-shelter/
<3>  system error: Permission denied; errno=13
We don't know why it differs from racket-minimal, but we don't care.
Solution: Remove heavy-tests from full-racket.
I.e., only add it when racket derivation is named racket-minimal.

 Problem: full-racket heavy-tests fails

---

build-racket.nix
catalog.nix
nix/racket2nix.rkt
racket-packages.nix
release.nix
stage0.nix
stage1.nix

openssl: x509-root-sources: cert sources do not exist: /no-cert-file.crt, /nix/store/nlb8hykwq7jc4vpnda39civ9cvrb7ymq-openssl-1.0.2p/etc/ssl/certs; override using SSL_CERT_FILE, SSL_CERT_DIR
It's only an annoyance -- we do not perform any network operations --
but it's the typical kind of warning message that might take someone
on a wild goose chase while troubleshooting.
Solution: Add `cacert` to the `buildInputs` of things running racket.
Allowing `cacert` to manipulate `SSL_CERT_FILE` is cleaner than
manipulating the variable directly. Modify the derivations that do.

Problem: Error messages about SSL certificates

---

README.adoc

It can never be up to date, but at this point it's pointing at a
several months old commit, from before we even fixed the cycle
detection.
Solution: Update README.

Problem: fetchgit example is quite outdated

---

bump-release-catalog.sh

We should use the racket the catalog is for.
Solution: Use nix-shell inside the script instead of as interpreter.
We cannot just skip using racket, as we did in #242 with the live
catalog, because the release catalog uses relative paths and we want
racket to sort that out for us.

Problem: bump-release-catalog uses system racket

---

nix/racket2nix-test.rkt
nix/racket2nix.rkt
racket-packages.nix

One regex is ambiguous (for humans), and has had this error from the
very beginning, or at least for as long as racket-packages.nix has
been checked in. We were just (un)lucky enough to not happen to be
depending on any of the affected packages, so we never noticed.
Solution: Add unit test for the regression, fix regex.

 Problem: We are parsing some github URLs wrong

---

nix/racket2nix.rkt
racket-packages.nix

Solution: Move the racket-index fix to postPatch.
This was patchPhase is intact, and users can override postPatch.
The racket-index patch should probably be moved out to default
overrides, but this is the minimal fix for the issue at hand.

Problem: patchPhase ignores pre/postPatch

---

.gitlab-ci.yml
release.sh

We do have a mirror repo on gitlab.com. It's nice if anyone forking
there gets feedback that Just Works, before even submitting a PR.
Also, fractalide/fractalide#362 .
Solution: Create .gitlab-ci.yml
There isn't much of anything to maintain, and it doesn't interfere
with anything else.
Thanks:
https://medium.com/plapadoo/using-nix-and-ci-for-great-good-8a9162fed313

 Problem: No GitLab CI support

---

nix/racket2nix.rkt
racket-packages.nix

You can find it by looking it up in the derivation.
Solution: Remove log spam.

Problem: log spam: racket-cmd

---

build-racket.nix
default.nix
test.nix

This makes it a bit obscure to use from e.g. test.nix.
We want to use racket-packages.nix to get the full catalog
and not only the subset of packages in the transitive dependencies,
because the #251 installCheckPhase will want compiler-lib to be
available when building e.g. br-parser-tools-lib.
Also regenerating the Nix expression is unnecessary work.
Solution: Put the functionality in buildRacket instead.
Make default.nix an ever thinner wrapper around build(Thin)Racket.

 Problem: racket-packages.nix shortcut only in default.nix

---

build-racket-default-overlay.nix
nix/racket2nix.rkt
racket-packages.nix

Solution: Run raco test on all rkt files when doInstallCheck enabled.
Adapted from the fractalide-tests target in Fractalide, but:
- Instead of creating a separate derivation it just creates an output.
- The test output is less spammy.
- Don't rely on parallel, xargs has parallelization too.
- Don't just show output in build output, it may interleave. Output
to per-file output files too.
Fractalide still can't make use of the complete generic mechanism,
because we have directories we want to skip. But the required work in
Fractalide gets reduced to enabling doInstallCheck and overriding
installCheckPhase, and that's an improvement too.

 Problem: No general mechanism for running package tests

---

build-racket-default-overlay.nix

Now that we have installCheck, we should use it on the packages that
benefit from it.
Solution: Add initial overrides based on what Fractalide uses.
Just a quick manual check of which packages actually run tests.

Problem: Packages in catalog not making use of installCheck

---

release.nix

It tries to run the tests, but the package is not there because it is
in the racket derivation.
There isn't much point in supporting racket-full, it was always just
'also there'. Actually, I thought I had already removed it. On
x86_64-darwin we don't even have one.
Solution: Remove racket-full jobs from release.nix.

Problem: pict-lib doesn't build with racket-full

---

update-racket-packages.sh

openssl: x509-root-sources: cert sources do not exist: [ . . . ]
Solution: Add cacert to script dependencies.

Problem: update-racket-packages: OpenSSL spam

---

nix/racket2nix.rkt
racket-packages.nix

To quote the bash manual:
The return status of a pipeline is the exit status of the last command [ . . . ]
Solution: Do not filter test output in a pipeline, use process substitution.

Problem: installCheck: Does not fail when tests fail

---

build-racket-default-overlay.nix
build-racket-racket2nix-overlay.nix
build-racket.nix
default.nix
pkgs/default.nix
release.nix
stage1.nix
update-racket2nix-overlay.sh

Because of how default.nix is set up, any use of buildRacket at all
involves bootstrapping and verifying racket2nix before you can get a
derivation or even a function.
The worst consequence of this right now is, when a build worker is
down, release.nix doesn't evaluate on hydra.
Solution: Make racket2nix from a static nix expression.
We check that the expression is up to date in release, just like with
racket-packages, and we do the full bootstrap and verification of
racket2nix in release only.

Problem: Too much going on during eval

---

.gitignore
update-racket-packages.sh

This may sound like an exotic use case, but when iteratively fixing
things, running multiple update-racket-packages in parallel actually
makes sense.
You try to build something, it fails in multiple dependencies. You fix
one thing, start updating racket-packages to then run a test build of
that thing. While that is running, you fix the next thing, and want to
run tests for that. Currently you need to wait for the first update to
finish before starting the next, or they trip over each other's .new
files.
Solution: Use unique temporary files.
Now, when one update finishes, it can start running its build. If
while it's updating you make more changes, you can start an update
based on those, and then build based on those changes as soon
as the second update is done. The latest finished update …

Problem: update-racket-packages not safe to run in parallel

---

build-racket-default-overlay.nix
build-racket-install-check-overlay.nix
build-racket.nix

The install-check-overrides simply overwrite any attributes earlier in
the overlay.
Solution: Make install-check-overrides their own overlay.
Order matters: racket2nix needs to come first, so that we can
eventually put it in install-check-overrides. default-overrides needs
to come after install-check-overrides so that the
overrideRacketDerivation in install-check-overrides doesn't discard
any overrideAttrs in default-overrides.

Problem: overrides: Not combined w/ install-check-overrides

---

catalog-exclusions.rktd
nix/racket2nix.rkt
update-catalog.sh

The most annoying part of running bump-all is that any new packages
with broken dependencies must be added to catalog-exclusions, and any
packages that have been fixed need to be removed. We can detect this
automatically.
Solution: update-catalog: Remove packages with missing transdeps.

Problem: catalog-exclusions needs manual attention

---

update-racket2nix-overlay.sh

In the sandbox there is no /usr/bin/env, so running ./racket2nix
inside a derivation fails.
Solution: update-racket2nix-overlay: Call ./racket2nix with explicit bash.
./release.sh now passes on NixOS.

Problem: racket2nix-overlay-updated: Cannot succeed on NixOS

---

build-racket-install-check-overrides.txt

It assumes that zip is at /usr/bin/zip.
Solution: Remove from install-check-overrides.

Problem: admiral-edu-server: Test cannot succeed in sandbox

---

build-racket-install-check-overrides.txt

- admiral-edu-server: Assumes that zip is at /usr/bin/zip.
- compatibility-test, contract-profile: Just fail without reporting
any failed tests.
Solution: Remove from install-check-overrides.
Now we have a green baseline for future changes.

Problem: failing installCheck tests

---

build-racket.nix
integration-tests/default.nix
nix/racket2nix.rkt
racket-packages.nix
release.nix

Simple tasks like copying a file from one place to another, or
processing some small text file, should not incur the overhead and
latency of talking to upstream caches or build workers. Just do it.
Solution: Set preferLocalBuild and allowSubstitutes where appropriate.
Applies to most runCommands, but not the ones in catalog.nix, which
are reasonably time-consuming.

Problem: Unproductive caching and remoting

---

build-racket.nix
catalog.nix
default.nix
integration-tests/default.nix
pkgs/default.nix
release.nix
stage0.nix
stage1.nix
test.nix

- When you do:
`nix-instantiate --eval -E 'builtins.attrNames (import ./pkgs {})'`
... you get all of nixpkgs in your face. This is not very friendly
when troubleshooting or otherwise looking around in the system. And
pkgs is what we export to users of the top-level expression too.
- We have implemented our own overlay system.
- We are repeating ourselves in headers: `, attr ? pkgs.attr`
These are remnants from early days and we know better now.
Solution: Use makeScope in pkgs, and mostly don't query pkgs directly.
Now we get a nice overview of what definitions we actually touched:
$ nix-instantiate --eval -E 'builtins.attrNames (import ./pkgs {})'
[ "buildDrvs" "buildRacket" "buildRacketCatalog" "buildRacketPackage"
"buildThinRacket" "buildThinRacketPackage" "callPackage" "newScope" …

Problem: Reinvented wheel, not being DRY, unfriendly attrs

---

release.nix

racket2nix-overlay-updated uses a crude approach to checking whether
the racket2nix-overlay is up-to-date. This is a good thing, because
it makes it insensitive to changes in exactly how the overlay is
expressed.
But it also makes it overly sensitive to irrelevant things like
symlinks in the directory. When diff sees a dangling symlink (like
a result symlink read in a sandbox) it treats it as an error.
Solution: Filter out symlinks.

Problem: release: overlay-updated sensitive to symlinks

---

update-catalog.sh

When putting together a long line of commits, it is helpful to be able
to batch-regenerate the various generated files in the repo using
`git rebase --exec`. When running, git-rebase sets `GIT_DIR` and
`GIT_WORK_TREE`, which make nix-prefetch-git want to reinitialize the
racket2nix repo rather than creating a fresh one in the temp dir, and
it confuses itself and bails out.
Currently the workaround is to remember to call update-catalog with
`env -u GIT_DIR -u GIT_WORK_TREE ./update-catalog.sh` during git
rebase.
Solution: Unset the git variables before calling racket2nix.
The real solution is to fix nix-prefetch-git upstream, I will create
an issue or PR for this.

Problem: update-catalog: Breaks when run inside git-rebase

---

catalog.rktd
nix/racket2nix.rkt
nixpkgs/bump.sh
nixpkgs/default.json
nixpkgs/default.nix
racket-packages.nix
racket2nix
release.nix
update-catalog.sh
update-racket-packages.sh
update-racket2nix-overlay.sh

This breaks all-checked-packages on Racket 7.2.
Solution: Add lookup.
* Bootstrap nixpkgs without <nixpkgs>, so nix-build can be called from
nix-shell --pure scripts.
* Make ./racket2nix use the pinned nixpkgs, so the version is accurate.
* Lookup package source by racket version.
Closes #94

 Problem: Not looking up package sources by racket version

---

nix/racket2nix.rkt
racket-packages.nix

To reproduce:
$ nix-build --no-out-link --argstr package errortrace-test -A env |
xargs bash -c '/bin/racket -N raco -l- raco test --help' _
[ . . . ]
raco: Unrecognized command: test
[ . . . ]
Solution: Run raco setup after setting up the environment.
The reason we weren't doing it was because it takes some time, I was
worried it might case recompilation errors in the dependencies, etc.
In fact, there are write attempts when processing the info-domains, but
their failures result in warnings only.
The crucial bit `setup` does is the `updating info-domain tables` bit.
We try to do as little as possible apart from that.
After:
$ nix-build --no-out-link --argstr package errortrace-test -A env |
xargs bash -c '/bin/racket -N raco -l- raco test --help' _
[ . . . ]
raco test [ <option> ... ] …

Problem: find-relevant-directories broken

---

integration-tests/default.nix

Since the 'fix' in 627a958b #273 the integration-test packages have
been confused about what to build, e.g. 'a' is part of a cycle, but
still tries to build from its own source.
$ ./release.sh -A tests.light-tests
[ . . . ]
for package: ./a
missing packages:
base
b
[ . . . ]
Solution: Override with overrideRacketDerivation.
Fudging with overrideAttrs upset some internal assumption. There is
work to do here on the derivation hygiene, for sure.
The error went undetected because of a bug in ./release.sh
(the -A tests.light-tests is required for the test to run).
Separate PR incoming.

Problem: integration-tests broken

---

.travis.yml
release.sh
support/utils/nix-build-travis-fold.sh

getOrder has been failing for a year, since 0dc6347 #141
In ./release.sh and Travis we fall back to only building the top-level
attributes in release.nix.
Solution: Feed release.nix the isTravis argument when evaluating.
* Fail louder and be more verbose about what is actually being built.
* Correctly detect tests.in.sub.attrs.

 Problem: ./release.sh and Travis are doing far too little

---

release.nix

Solution: Fail faster if the PR failed to update generated files.
Put -updated checks before the light-tests. If generated files are not
updated, the other tests mean nothing.

Problem: The most important test response does not come first

---

nix/racket2nix.rkt
racket-packages.nix
test.nix

Some packages cause the compiler to want to recompile dependencies, so
for those we have hijacked part of the circular-dependencies mechanism
to compile the dependency and the main package together, so that the
dependency is writable.
Some of this propagates. If e.g. racket-index has this issue
with scribble-lib, and you have this issue with racket-index, now you
need to add both packages to your writable dependencies.
Under 7.2 the manual effort is prohibitive, this occurs in too many
packages. Under 7.3 it gets even worse.
Solution: Detect when setup fails, retry with *all* deps writable.
Put the writable dependencies outside the derivation, so that
the issues doesn't propagate the same way (and also we have lighter
derivations, and no duplicates in the installed package set).
The …

 Problem: We have manually maintained compilation workarounds

---

release.sh

error: not an absolute path: './nixpkgs/result.drv'
Solution: Just remove that line, we don't actually need it.

Problem: release.sh broken

---

nixpkgs/bump.sh
nixpkgs/default.json
racket-packages.nix
release-catalog.json

Solution: Bump nixpkgs.
Racket 7.2 is not the latest, but someone might want to use it for
Reasons, so let's make a stop here on the way to 7.3.

Problem: Not using Racket 7.2

---

build-racket-install-check-overrides.txt

Breaks on overloaded system.
<3>--------------------
<3>Defer works with no delay
<3>FAILURE
<3>name:       check-true
<3>location:   main-test.rkt:10:3
<3>params:     '(#f)
<3>--------------------
Solution: Remove from tested packages.

Problem: deferred: test flaky, time-sensitive

---

nix/racket2nix.rkt
racket-packages.nix

These were put in the store during development for troubleshooting.
* They use up space until collected. This is of particular interest
for Travis runs.
* Actually when you want them the most is when a test failed, and
that's when the store *won't* be updated.
Solution: Put test artifacts in a temp directory instead.
* This may improve performance, if tmp is on tmpfs.
* When a test fails, look in the saved build directory for the
per-module test results.
Refactor: Use makeRacket for env setup.

 Problem: installCheck: test+testEnv in the store

---

nix/racket2nix.rkt
racket-packages.nix

* We are looking inside compiler-lib's dependencies.
* We are reimplementing racketConfigBuildInputs.
Solution: Use resolveThinInputs and racketConfigBuildInputs

Problem: installCheck: dep resolution not DRY

---

nix/racket2nix.rkt
racket-packages.nix

The bash process running raco test is named as the file it is testing,
so you can get a confusing error message along the lines of:
.../info.rkt: foo: unbound variable
What would an info.rkt want with a variable? It's bash that is using
the process name to label its error messages.
Solution: Add some context to the process name.

Problem: installCheck: Error output can be confusing

---

test.nix

br-parser-tools carries dozens of transitive Racket dependencies.
Solution: Remove br-parser-tools from light-tests.
* Use typed-map-lib for both the racket-packages case and the
racket2nix-generated case.

Problem: light-tests still too heavy

---

nix/racket2nix.rkt
racket-packages.nix

$ -E '(import <racket2nix> { package = "jack-ease"; }).overrideRacketDerivation (_: { doInstallCheck = true; })'
[ . . . ]
FAILURE
name:       check-all-documented
location:   doc-coverage.rkt:7:2
params:     '(ease)
Module ease has 9 undocumented bindings:
[ . . . ]
Solution: racoSetup the package under test.
Closes #292

Problem: racket-index check-docs fails in tests

---

nix/racket2nix.rkt
racket-packages.nix

The problem is that nixpkgs automatically sets `-rpath` pointers in
native libraries to `out`, but we keep our native libraries in `env`
together with the compiled racket libraries.
Our wrappers in `out` point to the libraries in `env`, so if the
libraries point back to `out` we get a circular dependency.
Solution: Rename the `env` output to `lib`.
nixpkgs `multiple-outputs.sh` prioritizes the `lib` output for rpaths over
`out` if it exists.
```
cycle detected in the references of '/nix/store/...-bcrypt-env' from '/nix/store/...-bcrypt'
error: build of '/nix/store/...-bcrypt.drv' failed
```

Problem: bcrypt out and env have a circular dependency

---

nix/racket2nix.rkt
racket-packages.nix

It's only supposed to have launchers created by the application.
If we would install two racket packages with nix-env, their racos
would collide.
Solution: Add raco to the exceptions from the symlinking.

Problem: We leave stray raco links in the out output

---

nix/racket2nix.rkt
racket-packages.nix

Solution: Sort the names of the packages in the cycle.
The transdeps mechanism used to do this before #306
36982f12a5c526a331c360368971703556f86207

Problem: Reified cycle packages do not have stable names

---

update-racket2nix-overlay.sh

Solution: Test that there is a first parameter before accessing it.

Problem: update-racket2nix-overlay: requires parameter

---

bump-release-catalog.sh

Just referring to `[ racket ]` actually never worked.
This means the script has always been running with whatever
`racket` happens to be on `$PATH`, rather than the recently
bumped racket it was supposed to be run with (if called from
`bump-all.sh`).
Solution: Call `nix-shell` with a proper `mkShell` environment.

Problem: bump-release-catalog is not run with pkgs.racket

---

bump-all.sh

This file was removed in:
a938f1667fd15b1620d4ef89f734f63c520f830c #308
Solution: Call the racket-packages target in update.nix.

Problem: bump-all calls the removed update-racket-packages.sh
